FROM mcr.microsoft.com/mssql/server:2022-latest

USER root
SHELL ["/bin/bash", "-c"]

# Install
RUN apt-get update &&  \
    apt-get install -y \
    curl && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

ENV PATH=$PATH:/opt/mssql-tools18/bin

WORKDIR /docker-entrypoint-initdb.d

COPY ./initdb.d/* /docker-entrypoint-initdb.d/
RUN chmod -R +x /docker-entrypoint-initdb.d

RUN curl -s -L -O https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorks2022.bak

EXPOSE 1433

ENTRYPOINT ["/bin/bash","./entrypoint.sh"]
